---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
rvm:
  - 1.8.7
  - 1.9.3
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
